# _quarto-alt.yml

project:
  type: book
  output-dir: docs

book:
  title: "The AI Jungle"
  subtitle: "Learn AI & ML with Nature's Wisdom"
  author: "Amit Verma"
  date: "2025-07-18"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter18.qmd


website:
  title: "The AI Jungle"
  repo-url: https://github.com/amitverma/TheQuantumMirror
  repo-actions: [edit, issue]
  site-url: https://amitverma.github.io/TheQuantumMirror/
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Intro"
        href: intro.qmd
      - text: "chapter1"
        href: chapter1.qmd
      - text: "chapter18"
        href: chapter18.qmd


format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    number-sections: true
    self-contained: true
